/**
 * Mock data for testing and application development.
 */

import {TimesheetEntry} from "@/components/ui/timesheet/DayEntry";

export const timesheetEntries: TimesheetEntry[] = [
  {
    id: 1,
    businessUnit: "Operations",
    asset: "Plant North",
    project: "Phoenix Upgrade",
    projectColor: 51,
    date: new Date(2026, 6, 1),
    hours: 8,
    comments: ["Closed out onboarding tickets and updated runbook notes.", "Needs additional work to be complete."],
  },
  {
    id: 2,
    businessUnit: "Operations",
    asset: "Plant South",
    project: "Atlas Migration",
    projectColor: 54,
    date: new Date(2026, 6, 2),
    hours: 9.5,
    comments: [],
  },
  {
    id: 3,
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Helios Reporting",
    projectColor: 60,
    date: new Date(2026, 6, 3),
    hours: 8,
    comments: ["Reviewed KPI dashboards and aligned report filters."],
  },
  {
    id: 4,
    businessUnit: "Corporate",
    asset: "HQ Systems",
    project: "Orion Compliance",
    projectColor: 5,
    date: new Date(2026, 6, 4),
    hours: 7,
    comments: ["Completed audit checklist prep and follow-up emails."],
  },
  {
    id: 5,
    businessUnit: "Corporate",
    asset: "Plant North",
    project: "Nova Rollout",
    projectColor: 7,
    date: new Date(2026, 6, 5),
    hours: 8,
    comments: ["Validated rollout tasks and captured release notes."],
  },
  {
    id: 6,
    businessUnit: "Corporate",
    asset: "Plant South",
    project: "Pulse Optimization",
    projectColor: 11,
    date: new Date(2026, 6, 6),
    hours: 10,
    comments: ["Optimized ETL timings and coordinated with QA on retests."],
  },
  {
    id: 7,
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Summit Integration",
    projectColor: 69,
    date: new Date(2026, 6, 7),
    hours: 8,
    comments: ["Integrated webhook handlers and verified retry behavior."],
  },
  {
    id: 8,
    businessUnit: "Corporate",
    asset: "HQ Systems",
    project: "Cedar Analytics",
    projectColor: 14,
    date: new Date(2026, 6, 8),
    hours: 2,
    comments: ["Refined event taxonomy and documented data definitions."],
  },
  {
    id: 9,
    businessUnit: "Operations",
    asset: "Plant North",
    project: "Phoenix Upgrade",
    projectColor: 51,
    date: new Date(2026, 6, 8),
    hours: 3,
    comments: ["Patched staging issues and confirmed smoke tests passed."],
  },
  {
    id: 10,
    businessUnit: "Corporate",
    asset: "Plant South",
    project: "Atlas Migration",
    projectColor: 16,
    date: new Date(2026, 6, 8),
    hours: 5,
    comments: ["Ran partial data validation and flagged mapping gaps."],
  },
  {
    id: 11,
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Helios Reporting",
    projectColor: 60,
    date: new Date(2026, 6, 8),
    hours: 8,
    comments: ["Built report drill-down links and checked access rules."],
  },
  {
    id: 12,
    businessUnit: "Corporate",
    asset: "HQ Systems",
    project: "Orion Compliance",
    projectColor: 5,
    date: new Date(2026, 6, 12),
    hours: 8,
    comments: ["Updated policy references and logged control evidence."],
  },
  {
    id: 13,
    businessUnit: "Operations",
    asset: "Plant North",
    project: "Nova Rollout",
    projectColor: 72,
    date: new Date(2026, 6, 13),
    hours: 8,
    comments: ["Supported rollout QA and resolved one regression defect."],
  },
  {
    id: 14,
    businessUnit: "Corporate",
    asset: "Plant South",
    project: "Pulse Optimization",
    projectColor: 11,
    date: new Date(2026, 6, 14),
    hours: 8,
    comments: ["Benchmarked query plans and documented tuning changes."],
  },
  {
    id: 15,
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Summit Integration",
    projectColor: 69,
    date: new Date(2026, 6, 15),
    hours: 8,
    comments: ["Completed integration sign-off and wrote handover notes."],
  },
];
