/**
 * Mock data for testing and application development.
 */

import {DayEntryProps} from "@/components/ui/timesheet/DayEntry";

export const timesheetEntries: DayEntryProps[] = [
  {
    id: "te-001",
    businessUnit: "Operations",
    asset: "Plant North",
    project: "Phoenix Upgrade",
    date: new Date("2026-07-01"),
    hours: 8,
    comments: ["Closed out onboarding tickets and updated runbook notes.", "Needs additional work to be complete."],
  },
  {
    id: "te-002",
    businessUnit: "Operations",
    asset: "Plant South",
    project: "Atlas Migration",
    date: new Date("2026-07-02"),
    hours: 9.5,
    comments: ["Handled migration dry run and fixed two blocking scripts."],
  },
  {
    id: "te-003",
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Helios Reporting",
    date: new Date("2026-07-03"),
    hours: 8,
    comments: ["Reviewed KPI dashboards and aligned report filters."],
  },
  {
    id: "te-004",
    businessUnit: "Corporate",
    asset: "HQ Systems",
    project: "Orion Compliance",
    date: new Date("2026-07-04"),
    hours: 7,
    comments: ["Completed audit checklist prep and follow-up emails."],
  },
  {
    id: "te-005",
    businessUnit: "Corporate",
    asset: "Plant North",
    project: "Nova Rollout",
    date: new Date("2026-07-05"),
    hours: 8,
    comments: ["Validated rollout tasks and captured release notes."],
  },
  {
    id: "te-006",
    businessUnit: "Corporate",
    asset: "Plant South",
    project: "Pulse Optimization",
    date: new Date("2026-07-06"),
    hours: 10,
    comments: ["Optimized ETL timings and coordinated with QA on retests."],
  },
  {
    id: "te-007",
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Summit Integration",
    date: new Date("2026-07-07"),
    hours: 8,
    comments: ["Integrated webhook handlers and verified retry behavior."],
  },
  {
    id: "te-008",
    businessUnit: "Corporate",
    asset: "HQ Systems",
    project: "Cedar Analytics",
    date: new Date("2026-07-08"),
    hours: 2,
    comments: ["Refined event taxonomy and documented data definitions."],
  },
  {
    id: "te-009",
    businessUnit: "Operations",
    asset: "Plant North",
    project: "Phoenix Upgrade",
    date: new Date("2026-07-08"),
    hours: 3,
    comments: ["Patched staging issues and confirmed smoke tests passed."],
  },
  {
    id: "te-010",
    businessUnit: "Corporate",
    asset: "Plant South",
    project: "Atlas Migration",
    date: new Date("2026-07-08"),
    hours: 5,
    comments: ["Ran partial data validation and flagged mapping gaps."],
  },
  {
    id: "te-011",
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Helios Reporting",
    date: new Date("2026-07-08"),
    hours: 8,
    comments: ["Built report drill-down links and checked access rules."],
  },
  {
    id: "te-012",
    businessUnit: "Corporate",
    asset: "HQ Systems",
    project: "Orion Compliance",
    date: new Date("2026-07-12"),
    hours: 8,
    comments: ["Updated policy references and logged control evidence."],
  },
  {
    id: "te-013",
    businessUnit: "Operations",
    asset: "Plant North",
    project: "Nova Rollout",
    date: new Date("2026-07-13"),
    hours: 8,
    comments: ["Supported rollout QA and resolved one regression defect."],
  },
  {
    id: "te-014",
    businessUnit: "Corporate",
    asset: "Plant South",
    project: "Pulse Optimization",
    date: new Date("2026-07-14"),
    hours: 8,
    comments: ["Benchmarked query plans and documented tuning changes."],
  },
  {
    id: "te-015",
    businessUnit: "Operations",
    asset: "Fleet West",
    project: "Summit Integration",
    date: new Date("2026-07-15"),
    hours: 8,
    comments: ["Completed integration sign-off and wrote handover notes."],
  },
];
